export const IPC_CHANNELS = {
  app: {
    getInfo: "assetwell:app:get-info",
  },
  higgsfield: {
    getStatus: "assetwell:higgsfield:get-status",
    signIn: "assetwell:higgsfield:sign-in",
    checkCredits: "assetwell:higgsfield:check-credits",
    checkWorkspace: "assetwell:higgsfield:check-workspace",
    listModels: "assetwell:higgsfield:list-models",
    getModelDetails: "assetwell:higgsfield:get-model-details",
    chooseAsset: "assetwell:higgsfield:choose-asset",
    uploadAsset: "assetwell:higgsfield:upload-asset",
    generate: "assetwell:higgsfield:generate",
    openOutput: "assetwell:higgsfield:open-output",
    cancelCommand: "assetwell:higgsfield:cancel-command",
    commandOutput: "assetwell:higgsfield:command-output",
  },
  library: {
    loadSnapshot: "assetwell:library:load-snapshot",
    saveSnapshot: "assetwell:library:save-snapshot",
    getSettings: "assetwell:library:get-settings",
    chooseOutputRoot: "assetwell:library:choose-output-root",
    revealOutputRoot: "assetwell:library:reveal-output-root",
    listReferenceAssets: "assetwell:library:list-reference-assets",
    importReferenceAssets: "assetwell:library:import-reference-assets",
    revealReferenceAssets: "assetwell:library:reveal-reference-assets",
    deleteReferenceAsset: "assetwell:library:delete-reference-asset",
    exportCreativeZip: "assetwell:library:export-creative-zip",
    exportVideo: "assetwell:library:export-video",
  },
  updater: {
    getDownloadedUpdate: "assetwell:updater:get-downloaded-update",
    installDownloadedUpdate: "assetwell:updater:install-downloaded-update",
    downloadedUpdate: "assetwell:updater:downloaded-update",
  },
} as const
