export const IPC_CHANNELS = {
  app: {
    getInfo: "assetwell:app:get-info",
    getCurrentReleaseNotes: "assetwell:app:get-current-release-notes",
  },
  higgsfield: {
    getStatus: "assetwell:higgsfield:get-status",
    signIn: "assetwell:higgsfield:sign-in",
    signOut: "assetwell:higgsfield:sign-out",
    checkCredits: "assetwell:higgsfield:check-credits",
    checkWorkspace: "assetwell:higgsfield:check-workspace",
    setWorkspace: "assetwell:higgsfield:set-workspace",
    listModels: "assetwell:higgsfield:list-models",
    getModelDetails: "assetwell:higgsfield:get-model-details",
    listUploads: "assetwell:higgsfield:list-uploads",
    chooseAsset: "assetwell:higgsfield:choose-asset",
    chooseAssets: "assetwell:higgsfield:choose-assets",
    createUpload: "assetwell:higgsfield:create-upload",
    uploadAsset: "assetwell:higgsfield:upload-asset",
    generate: "assetwell:higgsfield:generate",
    openOutput: "assetwell:higgsfield:open-output",
    cancelCommand: "assetwell:higgsfield:cancel-command",
    commandOutput: "assetwell:higgsfield:command-output",
  },
  library: {
    loadSnapshot: "assetwell:library:load-snapshot",
    saveSnapshot: "assetwell:library:save-snapshot",
    getSettings: "assetwell:library:get-settings",
    chooseOutputRoot: "assetwell:library:choose-output-root",
    revealOutputRoot: "assetwell:library:reveal-output-root",
    loadBrandState: "assetwell:library:load-brand-state",
    setActiveBrand: "assetwell:library:set-active-brand",
    createBrand: "assetwell:library:create-brand",
    updateBrand: "assetwell:library:update-brand",
    assignUploadsToBrand: "assetwell:library:assign-uploads-to-brand",
    loadUploadsSnapshot: "assetwell:library:load-uploads-snapshot",
    setActiveUploadWorkspace: "assetwell:library:set-active-upload-workspace",
    createUploadWorkspace: "assetwell:library:create-upload-workspace",
    updateUploadWorkspace: "assetwell:library:update-upload-workspace",
    deleteUploadWorkspace: "assetwell:library:delete-upload-workspace",
    importReferenceAssets: "assetwell:library:import-reference-assets",
    revealReferenceAssets: "assetwell:library:reveal-reference-assets",
    exportCreativeZip: "assetwell:library:export-creative-zip",
    exportVideo: "assetwell:library:export-video",
  },
  updater: {
    getDownloadedUpdate: "assetwell:updater:get-downloaded-update",
    installDownloadedUpdate: "assetwell:updater:install-downloaded-update",
    downloadedUpdate: "assetwell:updater:downloaded-update",
  },
} as const
